server:
  host: "0.0.0.0"
  port: "5100"

db:
  host: "postgres_test"
  port: "5432"
  username: "postgres"
  name: "todos_db"
  password: "123"
  sslmode: "disable"

redis:
  host: "redis_test"
  port: "6379"
  password: "redis123"
  db: 0

token:
  keys:
    privatekey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDV2dJQkFBS0JnR2U1QXB1SHpTVDlLM3dhUkxocUs5dXFlZXNHRzhic25iQkJoaEYzWmRpS3huWGtyWTlPCjR2YVFHTW1wdkMrRDBzNTBvT2NYb3REVlNjSStRZVNhamVOOWlGUmpPeEJCVzVhOG84dlB0Uk84VGVpdDEzR08KVkhSaXE3ZmFnT3l5MXNJZ0tTdFJHZVFUZjRzT1ZLTUQ2WlFabFFLWEtWS3phM1lDUU9PYStZdjlBZ01CQUFFQwpnWUEzeGR3SkZiVFJ0dkN6QXMwQS9OWW9nRHFlamVKUnpObmQ5TjNLZHBGbEp2b2dXcDZZK0twQ09xbVpocE9TCldTZjVxK3o1VmxST1J1SXFlSitsOVJWbUZxTWp2alQwQnpPWi9sNytidzY3MFMvQWRoazFOdFdDTEFjbWtWcC8KbC8rQW1oeEdEd2ZlNW1rY1dZS1M3UjVoYWtBeEdzTE1HSE9BZ0VrbFEvc3hBUUpCQUtxNGg1eldzMGxRaHZKcQpub3c5ZlVZaHQxdFEyRjBhcVg5akpHNG4yR2M4MjVhTTlsWHpQSEFNeXhQc1gyMTJzL3pGY0tqRmVyc0EzRnhWCmNnZTA5UlVDUVFDYmlPR2c5ZDVyc2tDSTVOL0FVZ1lwSks4SzIxMkIwQU8yd2RnNmlQVzFVZ0hJT1R3TUUrWUMKV2VvWDBsbm9DS2FENVlOd1hkMnpRdlZUeWtiL1RVVkpBa0JONXJBekdDRnRkZXB1R2NySk1aSEZlOE1nVHc2Nwp4VnZNdmgrMGlFZ09LODREcjhVRVNWNnR2cGk0T2FiOTJ5bWNVVGZzTzFpYWxuVDNTU0lrZENWVkFrQmpzeGkrCjd4eUdlSnI1cFl6d1lTUGwxOGdFODUwN0N6WjJQa2YzTGJnalpOQVRvdXlrNlZSMWlXR1BwNTFPS2Mxam13bm8KUzZORHQ5WSt3ZGxFNmlsUkFrQXlONldKK29QNERMMWpBdGRwVHNBV0ZVQlFjTXBTNGZxTFpxVGNRQmR3WGZ0NQpnMnE3VUJ5T0ZXbGNWNXpHMHVFemtFTUs0UnRHdzNzY2ZiS251RmhmCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t"
    publickey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZU1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTUFEQ0JpQUtCZ0dlNUFwdUh6U1Q5SzN3YVJMaHFLOXVxZWVzRwpHOGJzbmJCQmhoRjNaZGlLeG5Ya3JZOU80dmFRR01tcHZDK0QwczUwb09jWG90RFZTY0krUWVTYWplTjlpRlJqCk94QkJXNWE4bzh2UHRSTzhUZWl0MTNHT1ZIUmlxN2ZhZ095eTFzSWdLU3RSR2VRVGY0c09WS01ENlpRWmxRS1gKS1ZLemEzWUNRT09hK1l2OUFnTUJBQUU9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=="
  access:
    ttl: "10m"
  refresh:
    ttl: "24h"
    secondsTtl: 86400
    refreshCookiePath: "/auth/refresh"
    logoutCookiePath: "/auth/logout"

  