// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/auth-svc/internal/pb/auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*************************************
type RequestAdditionalInfo struct {
	UserAgent            string   `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SrcIpAddr            string   `protobuf:"bytes,2,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAdditionalInfo) Reset()         { *m = RequestAdditionalInfo{} }
func (m *RequestAdditionalInfo) String() string { return proto.CompactTextString(m) }
func (*RequestAdditionalInfo) ProtoMessage()    {}
func (*RequestAdditionalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{0}
}

func (m *RequestAdditionalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAdditionalInfo.Unmarshal(m, b)
}
func (m *RequestAdditionalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAdditionalInfo.Marshal(b, m, deterministic)
}
func (m *RequestAdditionalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAdditionalInfo.Merge(m, src)
}
func (m *RequestAdditionalInfo) XXX_Size() int {
	return xxx_messageInfo_RequestAdditionalInfo.Size(m)
}
func (m *RequestAdditionalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAdditionalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAdditionalInfo proto.InternalMessageInfo

func (m *RequestAdditionalInfo) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *RequestAdditionalInfo) GetSrcIpAddr() string {
	if m != nil {
		return m.SrcIpAddr
	}
	return ""
}

//****************************************************
type TokensInfo struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshCookiePath    string   `protobuf:"bytes,3,opt,name=refresh_cookie_path,json=refreshCookiePath,proto3" json:"refresh_cookie_path,omitempty"`
	LogoutCookiePath     string   `protobuf:"bytes,4,opt,name=logout_cookie_path,json=logoutCookiePath,proto3" json:"logout_cookie_path,omitempty"`
	RefreshCookieHost    string   `protobuf:"bytes,5,opt,name=refresh_cookie_host,json=refreshCookieHost,proto3" json:"refresh_cookie_host,omitempty"`
	LogoutCookieHost     string   `protobuf:"bytes,6,opt,name=logout_cookie_host,json=logoutCookieHost,proto3" json:"logout_cookie_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokensInfo) Reset()         { *m = TokensInfo{} }
func (m *TokensInfo) String() string { return proto.CompactTextString(m) }
func (*TokensInfo) ProtoMessage()    {}
func (*TokensInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{1}
}

func (m *TokensInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokensInfo.Unmarshal(m, b)
}
func (m *TokensInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokensInfo.Marshal(b, m, deterministic)
}
func (m *TokensInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokensInfo.Merge(m, src)
}
func (m *TokensInfo) XXX_Size() int {
	return xxx_messageInfo_TokensInfo.Size(m)
}
func (m *TokensInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokensInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokensInfo proto.InternalMessageInfo

func (m *TokensInfo) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *TokensInfo) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *TokensInfo) GetRefreshCookiePath() string {
	if m != nil {
		return m.RefreshCookiePath
	}
	return ""
}

func (m *TokensInfo) GetLogoutCookiePath() string {
	if m != nil {
		return m.LogoutCookiePath
	}
	return ""
}

func (m *TokensInfo) GetRefreshCookieHost() string {
	if m != nil {
		return m.RefreshCookieHost
	}
	return ""
}

func (m *TokensInfo) GetLogoutCookieHost() string {
	if m != nil {
		return m.LogoutCookieHost
	}
	return ""
}

//********************************************************
type RegisterRequest struct {
	Email                string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Phone                string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Fullname             string                 `protobuf:"bytes,5,opt,name=fullname,proto3" json:"fullname,omitempty"`
	RequestInfo          *RequestAdditionalInfo `protobuf:"bytes,6,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *RegisterRequest) GetRequestInfo() *RequestAdditionalInfo {
	if m != nil {
		return m.RequestInfo
	}
	return nil
}

type RegisterResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Uuid                 string      `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TokensInfo           *TokensInfo `protobuf:"bytes,4,opt,name=tokens_info,json=tokensInfo,proto3" json:"tokens_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RegisterResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterResponse) GetTokensInfo() *TokensInfo {
	if m != nil {
		return m.TokensInfo
	}
	return nil
}

//*************************************************
type LoginRequest struct {
	Email                string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RequestInfo          *RequestAdditionalInfo `protobuf:"bytes,3,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetRequestInfo() *RequestAdditionalInfo {
	if m != nil {
		return m.RequestInfo
	}
	return nil
}

type LoginResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Uuid                 string      `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TokensInfo           *TokensInfo `protobuf:"bytes,4,opt,name=tokens_info,json=tokensInfo,proto3" json:"tokens_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LoginResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LoginResponse) GetTokensInfo() *TokensInfo {
	if m != nil {
		return m.TokensInfo
	}
	return nil
}

//********************************************************************
type ValidateRequest struct {
	AccessToken          string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RequestInfo          *RequestAdditionalInfo `protobuf:"bytes,2,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{6}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ValidateRequest) GetRequestInfo() *RequestAdditionalInfo {
	if m != nil {
		return m.RequestInfo
	}
	return nil
}

type ValidateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{7}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ValidateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ValidateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

//********************************************************************
type RefreshTokensRequest struct {
	RefreshToken         string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RequestInfo          *RequestAdditionalInfo `protobuf:"bytes,2,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RefreshTokensRequest) Reset()         { *m = RefreshTokensRequest{} }
func (m *RefreshTokensRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokensRequest) ProtoMessage()    {}
func (*RefreshTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{8}
}

func (m *RefreshTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokensRequest.Unmarshal(m, b)
}
func (m *RefreshTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokensRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokensRequest.Merge(m, src)
}
func (m *RefreshTokensRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokensRequest.Size(m)
}
func (m *RefreshTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokensRequest proto.InternalMessageInfo

func (m *RefreshTokensRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshTokensRequest) GetRequestInfo() *RequestAdditionalInfo {
	if m != nil {
		return m.RequestInfo
	}
	return nil
}

type RefreshTokensResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TokensInfo           *TokensInfo `protobuf:"bytes,3,opt,name=tokens_info,json=tokensInfo,proto3" json:"tokens_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RefreshTokensResponse) Reset()         { *m = RefreshTokensResponse{} }
func (m *RefreshTokensResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokensResponse) ProtoMessage()    {}
func (*RefreshTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{9}
}

func (m *RefreshTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokensResponse.Unmarshal(m, b)
}
func (m *RefreshTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokensResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokensResponse.Merge(m, src)
}
func (m *RefreshTokensResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokensResponse.Size(m)
}
func (m *RefreshTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokensResponse proto.InternalMessageInfo

func (m *RefreshTokensResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefreshTokensResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RefreshTokensResponse) GetTokensInfo() *TokensInfo {
	if m != nil {
		return m.TokensInfo
	}
	return nil
}

//*********************************************************************
type InvalidateTokensRequest struct {
	RefreshToken         string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RequestInfo          *RequestAdditionalInfo `protobuf:"bytes,2,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InvalidateTokensRequest) Reset()         { *m = InvalidateTokensRequest{} }
func (m *InvalidateTokensRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidateTokensRequest) ProtoMessage()    {}
func (*InvalidateTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{10}
}

func (m *InvalidateTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateTokensRequest.Unmarshal(m, b)
}
func (m *InvalidateTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateTokensRequest.Marshal(b, m, deterministic)
}
func (m *InvalidateTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateTokensRequest.Merge(m, src)
}
func (m *InvalidateTokensRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidateTokensRequest.Size(m)
}
func (m *InvalidateTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateTokensRequest proto.InternalMessageInfo

func (m *InvalidateTokensRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *InvalidateTokensRequest) GetRequestInfo() *RequestAdditionalInfo {
	if m != nil {
		return m.RequestInfo
	}
	return nil
}

type InvalidateTokensResponse struct {
	TokensInfo           *TokensInfo `protobuf:"bytes,1,opt,name=tokens_info,json=tokensInfo,proto3" json:"tokens_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InvalidateTokensResponse) Reset()         { *m = InvalidateTokensResponse{} }
func (m *InvalidateTokensResponse) String() string { return proto.CompactTextString(m) }
func (*InvalidateTokensResponse) ProtoMessage()    {}
func (*InvalidateTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb02580938ec900a, []int{11}
}

func (m *InvalidateTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateTokensResponse.Unmarshal(m, b)
}
func (m *InvalidateTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateTokensResponse.Marshal(b, m, deterministic)
}
func (m *InvalidateTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateTokensResponse.Merge(m, src)
}
func (m *InvalidateTokensResponse) XXX_Size() int {
	return xxx_messageInfo_InvalidateTokensResponse.Size(m)
}
func (m *InvalidateTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateTokensResponse proto.InternalMessageInfo

func (m *InvalidateTokensResponse) GetTokensInfo() *TokensInfo {
	if m != nil {
		return m.TokensInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestAdditionalInfo)(nil), "auth.RequestAdditionalInfo")
	proto.RegisterType((*TokensInfo)(nil), "auth.TokensInfo")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*ValidateRequest)(nil), "auth.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "auth.ValidateResponse")
	proto.RegisterType((*RefreshTokensRequest)(nil), "auth.RefreshTokensRequest")
	proto.RegisterType((*RefreshTokensResponse)(nil), "auth.RefreshTokensResponse")
	proto.RegisterType((*InvalidateTokensRequest)(nil), "auth.InvalidateTokensRequest")
	proto.RegisterType((*InvalidateTokensResponse)(nil), "auth.InvalidateTokensResponse")
}

func init() {
	proto.RegisterFile("services/auth-svc/internal/pb/auth.proto", fileDescriptor_eb02580938ec900a)
}

var fileDescriptor_eb02580938ec900a = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0xed, 0xa4, 0x69, 0xbf, 0xf4, 0x26, 0x55, 0xf3, 0xb9, 0x2d, 0x44, 0x53, 0xb5, 0xd0, 0x61,
	0xd3, 0x05, 0x24, 0xa2, 0x2c, 0x2b, 0x21, 0x05, 0x36, 0x14, 0x81, 0x84, 0xa6, 0xa8, 0x0b, 0x36,
	0x23, 0x77, 0xc6, 0xc9, 0x58, 0x9d, 0xda, 0x83, 0xed, 0x29, 0x12, 0x48, 0x88, 0x15, 0x12, 0x3b,
	0x5e, 0x8b, 0x77, 0xe0, 0x61, 0xd0, 0xf8, 0x27, 0x4d, 0x66, 0x52, 0x68, 0x0b, 0x52, 0x77, 0xbe,
	0x3f, 0x3e, 0xf7, 0x9e, 0xe3, 0x6b, 0x1b, 0xf6, 0x24, 0x11, 0xe7, 0x34, 0x26, 0x72, 0x80, 0x0b,
	0x95, 0x3e, 0x92, 0xe7, 0xf1, 0x80, 0x32, 0x45, 0x04, 0xc3, 0xd9, 0x20, 0x3f, 0xd1, 0xce, 0x7e,
	0x2e, 0xb8, 0xe2, 0xa8, 0x59, 0xae, 0x83, 0x63, 0xd8, 0x0c, 0xc9, 0xfb, 0x82, 0x48, 0x35, 0x4c,
	0x12, 0xaa, 0x28, 0x67, 0x38, 0x3b, 0x64, 0x23, 0x8e, 0xb6, 0x01, 0x0a, 0x49, 0x44, 0x84, 0xc7,
	0x84, 0xa9, 0x9e, 0x77, 0xdf, 0xdb, 0x5b, 0x09, 0x57, 0x4a, 0xcf, 0xb0, 0x74, 0xa0, 0x1d, 0x68,
	0x4b, 0x11, 0x47, 0x34, 0x8f, 0x70, 0x92, 0x88, 0x5e, 0xc3, 0xc4, 0xa5, 0x88, 0x0f, 0xf3, 0x61,
	0x92, 0x88, 0xe0, 0x7b, 0x03, 0xe0, 0x2d, 0x3f, 0x25, 0x4c, 0x6a, 0xb4, 0x5d, 0xe8, 0xe0, 0x38,
	0x26, 0x52, 0x46, 0xaa, 0x74, 0x5a, 0xbc, 0xb6, 0xf1, 0xe9, 0x3c, 0xf4, 0x00, 0x56, 0x05, 0x19,
	0x09, 0x22, 0x53, 0x9b, 0x63, 0x30, 0x3b, 0xd6, 0x69, 0x92, 0xfa, 0xb0, 0xee, 0x92, 0x62, 0xce,
	0x4f, 0x29, 0x89, 0x72, 0xac, 0xd2, 0xde, 0xa2, 0x4e, 0xfd, 0xdf, 0x86, 0x9e, 0xeb, 0xc8, 0x1b,
	0xac, 0x52, 0xf4, 0x10, 0x50, 0xc6, 0xc7, 0xbc, 0x50, 0x33, 0xe9, 0x4d, 0x9d, 0xde, 0x35, 0x91,
	0xa9, 0xec, 0x3a, 0x7a, 0xca, 0xa5, 0xea, 0x2d, 0xcd, 0x41, 0x7f, 0xc1, 0xa5, 0xaa, 0xa3, 0xeb,
	0xf4, 0xe5, 0x3a, 0x7a, 0x99, 0x1d, 0xfc, 0xf0, 0x60, 0x2d, 0x24, 0x63, 0x2a, 0x15, 0x11, 0x56,
	0x73, 0xb4, 0x01, 0x4b, 0xe4, 0x0c, 0xd3, 0xcc, 0x0a, 0x62, 0x0c, 0xe4, 0x43, 0x2b, 0xc7, 0x52,
	0x7e, 0xe0, 0x22, 0xb1, 0x2a, 0x4c, 0x6c, 0x84, 0xa0, 0x29, 0x78, 0x46, 0x2c, 0x65, 0xbd, 0x2e,
	0x51, 0xf2, 0x94, 0x33, 0x62, 0x89, 0x19, 0xa3, 0x44, 0x19, 0x15, 0x59, 0xc6, 0xf0, 0x19, 0xb1,
	0x14, 0x26, 0x36, 0x7a, 0x0a, 0x1d, 0x61, 0x5a, 0x88, 0x28, 0x1b, 0x71, 0xdd, 0x73, 0x7b, 0x7f,
	0xab, 0xaf, 0xe7, 0x63, 0xee, 0x40, 0x84, 0x6d, 0xbb, 0xa1, 0x34, 0x82, 0x6f, 0x1e, 0x74, 0x2f,
	0xb8, 0xc8, 0x9c, 0x33, 0x49, 0x50, 0x0f, 0xfe, 0x93, 0x85, 0x3e, 0x51, 0x4d, 0xa7, 0x15, 0x3a,
	0x53, 0xd3, 0x14, 0x82, 0xbb, 0x39, 0x31, 0x46, 0x49, 0xa5, 0x28, 0x68, 0xe2, 0xa8, 0x94, 0x6b,
	0xf4, 0x18, 0xda, 0xfa, 0xf4, 0xa5, 0xe9, 0xab, 0xa9, 0xfb, 0xea, 0x9a, 0xbe, 0x2e, 0xe6, 0x29,
	0x04, 0x35, 0x59, 0x07, 0x5f, 0x3c, 0xe8, 0xbc, 0xe2, 0x63, 0xca, 0x6e, 0x2e, 0x6a, 0x55, 0x8e,
	0xc5, 0x6b, 0xca, 0xf1, 0xd5, 0x83, 0x55, 0xdb, 0xc2, 0xed, 0x6a, 0xa1, 0x60, 0xed, 0x18, 0x67,
	0x34, 0xc1, 0x8a, 0x38, 0x35, 0xae, 0x70, 0xf5, 0xaa, 0xf4, 0x1b, 0xd7, 0xa4, 0x7f, 0x0c, 0xdd,
	0x8b, 0xaa, 0xff, 0x4e, 0x80, 0xe0, 0x13, 0x6c, 0x84, 0x53, 0xb7, 0x5f, 0x3a, 0x4a, 0xb5, 0xa7,
	0xc2, 0x9b, 0xf3, 0x54, 0xfc, 0x2d, 0xa9, 0x8f, 0xe5, 0xcb, 0x38, 0x53, 0xfc, 0x86, 0xcc, 0x2a,
	0xc7, 0xb8, 0x78, 0x85, 0x63, 0xfc, 0x0c, 0x77, 0x0f, 0xd9, 0xb9, 0x95, 0xf4, 0x16, 0xb8, 0xbf,
	0x86, 0x5e, 0xbd, 0xbe, 0xa5, 0x5f, 0xa1, 0xe3, 0xfd, 0x99, 0xce, 0xfe, 0xcf, 0x06, 0xb4, 0x87,
	0x85, 0x4a, 0x8f, 0xcc, 0xdf, 0x84, 0x0e, 0xa0, 0xe5, 0x1e, 0x0f, 0xb4, 0xe9, 0x9a, 0x9a, 0x79,
	0x18, 0xfd, 0x3b, 0x55, 0xb7, 0xa9, 0x1e, 0x2c, 0xa0, 0x7d, 0x58, 0xd2, 0x57, 0x0d, 0x21, 0x93,
	0x32, 0x7d, 0xf5, 0xfd, 0xf5, 0x19, 0xdf, 0x64, 0xcf, 0x01, 0xb4, 0xdc, 0x80, 0xba, 0x82, 0x95,
	0x6b, 0xe2, 0x0a, 0x56, 0xe7, 0x38, 0x58, 0x40, 0x2f, 0x61, 0x75, 0x66, 0x10, 0x90, 0xef, 0x7a,
	0xab, 0x8f, 0xa6, 0xbf, 0x35, 0x37, 0x36, 0xc1, 0x3a, 0x82, 0x6e, 0x55, 0x58, 0xb4, 0x6d, 0xb6,
	0x5c, 0x72, 0xe0, 0xfe, 0xce, 0x65, 0x61, 0x07, 0xfa, 0x6c, 0xf7, 0xdd, 0xbd, 0xfe, 0xe0, 0xb7,
	0xff, 0xfe, 0xc9, 0xb2, 0xfe, 0xf3, 0x9f, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x9f, 0x19,
	0xef, 0x1f, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	RefreshTokens(ctx context.Context, in *RefreshTokensRequest, opts ...grpc.CallOption) (*RefreshTokensResponse, error)
	InvalidateTokens(ctx context.Context, in *InvalidateTokensRequest, opts ...grpc.CallOption) (*InvalidateTokensResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshTokens(ctx context.Context, in *RefreshTokensRequest, opts ...grpc.CallOption) (*RefreshTokensResponse, error) {
	out := new(RefreshTokensResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/RefreshTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InvalidateTokens(ctx context.Context, in *InvalidateTokensRequest, opts ...grpc.CallOption) (*InvalidateTokensResponse, error) {
	out := new(InvalidateTokensResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/InvalidateTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	RefreshTokens(context.Context, *RefreshTokensRequest) (*RefreshTokensResponse, error)
	InvalidateTokens(context.Context, *InvalidateTokensRequest) (*InvalidateTokensResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (*UnimplementedAuthServiceServer) RefreshTokens(ctx context.Context, req *RefreshTokensRequest) (*RefreshTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshTokens not implemented")
}
func (*UnimplementedAuthServiceServer) InvalidateTokens(ctx context.Context, req *InvalidateTokensRequest) (*InvalidateTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateTokens not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/RefreshTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshTokens(ctx, req.(*RefreshTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InvalidateTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InvalidateTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/InvalidateTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InvalidateTokens(ctx, req.(*InvalidateTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
		{
			MethodName: "RefreshTokens",
			Handler:    _AuthService_RefreshTokens_Handler,
		},
		{
			MethodName: "InvalidateTokens",
			Handler:    _AuthService_InvalidateTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/auth-svc/internal/pb/auth.proto",
}
