version: '3'

services:
  main-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: todos-api-image:1.0.0
    container_name: todos_api_test
    command: ./migrations.bin && ./todos.bin
    depends_on:
      - postgres
      - redis
    ports:
      - 5100:5100

  postgres:
    image: postgres:12.12
    container_name: postgres_test
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./app.env

  redis:
    image: redis:6.2.10
    container_name: redis_test
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass "redis123"

      